import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./componenets/navbar"
import Foot from "./componenets/footer";
// import { Inter } from '@next/font/google'

// const inter = Inter({
//   subsets: ['latin'],
//   weight: ['700'],
// })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const inter = Inter({
// })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        {children}
        <Foot/>
      </body>
    </html>
  );
}
